Fix postinst script

diff --git a/rust/gateway/debian/postinst b/rust/gateway/debian/postinst
--- a/rust/gateway/debian/postinst
+++ b/rust/gateway/debian/postinst
@@ -1,7 +1,12 @@
-# Post-installation script run by apt
+#!/usr/bin/env bash
 
-# Create the necessary users
-systemd-sysusers
+# Script inspired by deb helper script from `cargo-deb`
+if [ "$1" = "configure" ] || [ "$1" = "abort-upgrade" ] || [ "$1" = "abort-deconfigure" ] || [ "$1" = "abort-remove" ] ; then
+	# In case this system is running systemd, we need to ensure that all
+	# necessary users are created before starting.
+	if [ -d /run/systemd/system ] ; then
+		systemd-sysusers firezone-gateway.conf >/dev/null || true
+	fi
+fi
 
-# Create the necessary directories
-systemd-tmpfiles --create
+#DEBHELPER#
