Remove pre-configured Okta & Google OAuth providers, update docs

diff --git a/omnibus/package-scripts/firezone/preinst b/omnibus/package-scripts/firezone/preinst
--- a/omnibus/package-scripts/firezone/preinst
+++ b/omnibus/package-scripts/firezone/preinst
@@ -17,6 +17,18 @@ kernelCheck() {
   fi
 }
 
+configCheck() {
+    config_file='/etc/firezone/firezone.rb'
+    error_color='\033[0;31m'
+    reset_color='\033[0m'
+
+    if grep -q "^\s*default\['firezone'\]\['authentication'\]\['\(google\|okta\)'\]\['enabled'\]\s*=\s*true" $config_file ; then
+        echo "${error_color}ERROR: Firezone 0.5+ disables support for pre-configured Okta and Google OAuth2 providers!${reset_color}"
+        echo "Please see our transition guide to move to a generic OIDC config: https://docs.firezone.dev/administer/upgrade#upgrading-from--050-to-050"
+        exit 1
+    fi
+}
+
 capture () {
   if type curl > /dev/null; then
     if [ -e /var/opt/firezone/cache/telemetry_id ]; then
@@ -40,5 +52,6 @@ if [ ! -e /var/opt/firezone/.disable_telemetry ]; then
   capture || true
 fi
 
-echo "You're about to install firezone!"
 kernelCheck
+configCheck
+echo "You're about to install firezone!"
