chore(portal): Add elixir code coverage config (#11128)
Why:

* With the recent large refactor we're now in a place of having many
tests that are either irrelevant or are not passing. This will require
rewriting many tests in a lot of cases. In this commit I've moved all of
the test files that have some type of failure to `.old` I've also made
sure that the code coverage tooling is configured for our elixir app.
This should allow us to have a quick gauge of where we're lacking as we
rewrite tests for all of the elixir apps.

Related: #11056

diff --git a/.github/workflows/_elixir.yml b/.github/workflows/_elixir.yml
--- a/.github/workflows/_elixir.yml
+++ b/.github/workflows/_elixir.yml
@@ -20,35 +20,28 @@ jobs:
       - uses: ./.github/actions/setup-elixir
         with:
           mix_env: ${{ env.MIX_ENV }}
+
       - name: Compile Application
         # run: mix compile --warnings-as-errors TODO: IDP-REFACTOR re-enable warnings-as-errors
         run: mix compile
+
       - name: Setup Database
         run: |
           mix ecto.create
           mix ecto.migrate
-      - name: Run Tests
+
+      - name: Run Tests with Coverage
         env:
           E2E_DEFAULT_WAIT_SECONDS: 20
           CI_ASSERT_RECEIVE_TIMEOUT_MS: 250
         run: |
-          # TODO: IDP REFACTOR
-          mix test apps/api/test/api/client/channel_test.exs
-          mix test apps/api/test/api/gateway/channel_test.exs
-          mix test apps/api/test/api/relay/channel_test.exs
-          mix test apps/api/test/api/controllers
-          mix test apps/domain/test/domain/auth_test.exs
-          mix test apps/domain/test/domain/gateway_token_test.exs
-          mix test apps/web/test/web/email_otp_test.exs
-          mix test apps/web/test/web/controllers/email_otp_controller_test.exs
+          # TODO: IDP-REFACTOR make sure to re-enable the --warnings-as-errors flag
+          mix coveralls.github --exclude flaky:true --exclude acceptance:true || \
+          mix coveralls.github --exclude flaky:true --exclude acceptance:true --failed
 
-          # mix_test="mix test --warnings-as-errors --exclude flaky:true --exclude acceptance:true"
-          # $mix_test || $mix_test --failed
       - name: Test Report
+        if: github.event.pull_request.head.repo.full_name == github.repository && (success() || failure())
         uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3 # v2.1.1
-        if:
-          ${{ github.event.pull_request.head.repo.full_name == github.repository
-          && (success() || failure()) }}
         with:
           name: Elixir Unit Test Report
           path: elixir/_build/test/lib/*/test-junit-report.xml
@@ -69,26 +62,30 @@ jobs:
         id: setup-beam
         with:
           mix_env: ${{ env.MIX_ENV }}
+
       - name: Compile Application
         run: mix compile --warnings-as-errors
-      - uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
-        name: Restore PLT cache
+
+      - name: Restore PLT cache
         id: plt_cache
+        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
         with:
           path: elixir/priv/plts
           key: dialyzer-ubuntu-24.04-${{ runner.arch }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ steps.setup-beam.outputs.otp-version }}-${{ hashFiles('elixir/mix.lock') }}
           # This will make sure that we can incrementally build the PLT from older cache and save it under a new key
-          restore-keys: |
-            dialyzer-ubuntu-24.04-${{ runner.arch }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ steps.setup-beam.outputs.otp-version }}-
+          restore-keys: dialyzer-ubuntu-24.04-${{ runner.arch }}-${{ steps.setup-beam.outputs.elixir-version }}-${{ steps.setup-beam.outputs.otp-version }}-
+
       - name: Create PLTs
         if: ${{ steps.plt_cache.outputs.cache-hit != 'true' }}
         run: mix dialyzer --plt
-      - uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
-        if: ${{ github.ref_name == 'main' }}
-        name: Save PLT cache
+
+      - name: Save PLT cache
+        if: github.ref_name == 'main'
+        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
         with:
           key: ${{ steps.plt_cache.outputs.cache-primary-key }}
           path: elixir/priv/plts
+
       - name: Run Dialyzer
         run: mix dialyzer --format dialyxir
 
@@ -105,21 +102,28 @@ jobs:
       - uses: ./.github/actions/setup-elixir
         with:
           mix_env: ${{ env.MIX_ENV }}
+
       - name: Compile Application
         run: |
           # TODO: Re-enable --force when we fix all warnings
           mix compile # --force --warnings-as-errors
+
       - name: Check Formatting
         run: mix format --check-formatted
+
       - name: Check For Retired Packages
         run: mix hex.audit
+
       - name: Check For Vulnerable Packages
         run: mix deps.audit
+
       - name: Run Sobelow vulnerability scanner for web app
         working-directory: ./elixir/apps/web
         run: mix sobelow --skip
+
       - name: Run Credo
         run: mix credo --strict
+
       - name: Check for unused deps
         run: mix deps.unlock --check-unused
 
@@ -134,19 +138,25 @@ jobs:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     steps:
       - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
+
       - uses: ./.github/actions/setup-postgres
+
       - uses: ./.github/actions/setup-elixir
         with:
           mix_env: ${{ env.MIX_ENV }}
+
       - name: Compile
         run: |
           # TODO: IDP REFACTOR
           #  revert
           mix compile # --warnings-as-errors
+
       - name: Generate self-signed cert
         run: cd apps/web && mix phx.gen.cert
+
       - name: Create Database
         run: mix ecto.create
+
       - name: Migrate DB to base ref and seed
         run: |
           git fetch --depth=1 origin ${{ github.base_ref }}
@@ -154,6 +164,7 @@ jobs:
           mix deps.get
           mix ecto.migrate
           mix ecto.seed
+
       # Then checkout current ref and rerun migrations
       - name: Run new migrations
         run: |
@@ -167,21 +178,21 @@ jobs:
   # TODO: IDP-REFACTOR: Re-enable
   # acceptance-test:
   #   name: acceptance-test-${{ matrix.MIX_TEST_PARTITION }}
-  #   permissions:
-  #     checks: write
   #   runs-on: ubuntu-24.04
   #   defaults:
   #     run:
   #       working-directory: ./elixir
+  #   permissions:
+  #     checks: write
+  #   strategy:
+  #     fail-fast: ${{ github.event_name == 'merge_group' }}
+  #     matrix:
+  #       MIX_TEST_PARTITION: [1]
   #   env:
   #     MIX_ENV: test
   #     POSTGRES_HOST: localhost
   #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   #     MIX_TEST_PARTITIONS: 1
-  #   strategy:
-  #     fail-fast: ${{ github.event_name == 'merge_group' }}
-  #     matrix:
-  #       MIX_TEST_PARTITION: [1]
   #   services:
   #     vault:
   #       image: vault:1.12.2
@@ -195,33 +206,42 @@ jobs:
   #     - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
   #     - uses: ./.github/actions/setup-postgres
   #     - uses: nanasess/setup-chromedriver@e93e57b843c0c92788f22483f1a31af8ee48db25 # v2.3.0
-  #     - run: |
+  #
+  #     - name: Setup Xvfb and ChromeDriver
+  #       run: |
   #         export DISPLAY=:99
   #         chromedriver --url-base=/wd/hub &
   #         sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 &
+  #
   #     - uses: ./.github/actions/setup-elixir
   #       with:
   #         mix_env: ${{ env.MIX_ENV }}
+  #
   #     - uses: ./.github/actions/setup-node
   #       with:
   #         npmjs-token: ${{ secrets.NPMJS_TOKEN }}
   #         lockfile-dir: ./elixir/apps/web/assets
+  #
   #     - name: Compile Application
   #       # run: mix compile --warnings-as-errors TODO: IPD-REFACOR re-enable warnings-as-errors
   #       run: mix compile
+  #
   #     - name: Install Front-End Dependencies
   #       run: |
   #         cd apps/web
   #         mix assets.setup
+  #
   #     - name: Build Web Assets
   #       run: |
   #         cd apps/web
   #         mix assets.build
+  #
   #     # Run tests
   #     - name: Setup Database
   #       run: |
   #         mix ecto.create
   #         mix ecto.migrate
+  #
   #     - name: Run Acceptance Tests
   #       env:
   #         MIX_TEST_PARTITION: ${{ matrix.MIX_TEST_PARTITION }}
@@ -236,19 +256,17 @@ jobs:
   #             || mix test --only acceptance:true --failed \
   #             || pkill -f chromedriver \
   #             || mix test --only acceptance:true --failed
+  #
   #     - name: Save Screenshots
-  #       if:
-  #         ${{ github.event.pull_request.head.repo.full_name == github.repository
-  #         && always() }}
+  #       if: ${{ github.event.pull_request.head.repo.full_name == github.repository && always() }}
   #       uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5.0.0
   #       with:
   #         name: screenshots-${{ matrix.MIX_TEST_PARTITION }}
   #         path: elixir/apps/web/screenshots
+  #
   #     - name: Test Report
+  #       if: ${{ github.event.pull_request.head.repo.full_name == github.repository && (success() || failure()) }}
   #       uses: dorny/test-reporter@dc3a92680fcc15842eef52e8c4606ea7ce6bd3f3 # v2.1.1
-  #       if:
-  #         ${{ github.event.pull_request.head.repo.full_name == github.repository
-  #         && (success() || failure()) }}
   #       with:
   #         name: Elixir Acceptance Test Report
   #         path: elixir/_build/test/lib/*/test-junit-report.xml
