ci(windows): run the Windows smoke test in CI

diff --git a/.github/workflows/_rust.yml b/.github/workflows/_rust.yml
--- a/.github/workflows/_rust.yml
+++ b/.github/workflows/_rust.yml
@@ -68,6 +68,41 @@ jobs:
       - uses: ./.github/actions/setup-rust
       - run: cargo test --all-features ${{ matrix.packages }}
 
+  # TODO: Naming
+  # Runs the Windows client smoke test, built in debug mode. We can't run it in release
+  # mode because of a known issue: <https://github.com/firezone/firezone/blob/456e044f882c2bb314e19cc44c0d19c5ad817b7c/rust/windows-client/src-tauri/src/client.rs#L162-L164>
+  windows-smoke-test:
+    name: windows-smoke-test
+    runs-on: windows-2019
+    defaults:
+      run:
+        working-directory: ./rust/windows-client
+    strategy:
+      fail-fast: false
+    env:
+      RUST_LOG=firezone_windows_client=info
+    steps:
+      - uses: actions/checkout@v4
+      - uses: ./.github/actions/setup-node
+      - uses: ./.github/actions/setup-rust
+        with:
+          targets: x86_64-pc-windows-msvc
+      - name: Run smoke test
+        run: |
+          # Run smoke test
+
+          # Copied from `build.bat`, but I don't want to run `tauri build`
+          pnpm install
+          cp "node_modules/flowbite/dist/flowbite.min.js" "src/"
+          pnpm tsc
+          pnpm tailwindcss -i src/input.css -o src/output.css
+
+          cargo run -p firezone-windows-client -- smoke-test
+          if (-not $?) {
+            echo "Smoke test failed."
+            exit 1
+          }
+
   # This should be identical to `build-push-windows-release-artifacts` in `cd.yml` except for the Github permissions, needs tag, and uploading step
   build-tauri:
     name: build-tauri-${{ matrix.artifact }}
