Fix formatting

diff --git a/.github/workflows/_static-analysis.yml b/.github/workflows/_static-analysis.yml
--- a/.github/workflows/_static-analysis.yml
+++ b/.github/workflows/_static-analysis.yml
@@ -7,16 +7,25 @@ jobs:
     runs-on: ubuntu-22.04
     steps:
       - name: Check PR title
-        if: ${{
-          github.event.pull_request
-          && !startsWith(github.event.pull_request.title, "feat")
-          && !startsWith(github.event.pull_request.title, "fix")
-          && !startsWith(github.event.pull_request.title, "refactor")
-          && !startsWith(github.event.pull_request.title, "chore")
-          && !startsWith(github.event.pull_request.title, "docs")
-          && !startsWith(github.event.pull_request.title, "security")
-          && !startsWith(github.event.pull_request.title, "deps") }}
-        run: echo "Invalid PR title ${{ github.event.pull_request.title }}. Must be one of: feat, fix, refactor, chore, docs, security, deps" && exit 1
+        if: ${{ github.event.pull_request }}
+        env:
+          VALID_PREFIXES: |
+            feat
+            fix
+            refactor
+            chore
+            docs
+            security
+            deps
+        run: |
+          for prefix in $VALID_PREFIXES; do
+            if [[ "${{ github.event.pull_request.title }}" == "$prefix"* ]]; then
+              echo "PR title ${{ github.event.pull_request.title }} is valid"
+              exit 0
+            fi
+          done
+          echo "Invalid PR title ${{ github.event.pull_request.title }}. Must be one of: feat, fix, refactor, chore, docs, security, deps"
+          exit 1
   version-check:
     runs-on: macos-14
     steps:
