Alias python=python3

diff --git a/.github/workflows/e2e.yml b/.github/workflows/e2e.yml
--- a/.github/workflows/e2e.yml
+++ b/.github/workflows/e2e.yml
@@ -163,6 +163,13 @@ jobs:
           build-root-directory: ./kotlin/android
       - run: |
           echo 'sdk.dir=/home/firezone/Android/Sdk' > local.properties
+
+          # Needed on Ubuntu 22.04
+          if ! type python > /dev/null; then
+            echo "'python' not found, aliasing python3"
+            alias python="python3"
+          fi
+
           ./gradlew --info assembleDebug bundleDebug
 
   ios:
