Split acceptance cases in separate job and run multiple partitions of it

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -25,6 +25,80 @@ jobs:
           --health-interval 10s
           --health-timeout 5s
           --health-retries 5
+    steps:
+      - name: Install package dependencies
+        run: |
+          sudo apt-get install -q -y \
+            net-tools \
+            wireguard
+      - uses: actions/checkout@v3
+      - uses: erlef/setup-beam@v1
+        with:
+          otp-version: '25'
+          elixir-version: '1.14'
+      - uses: actions/cache@v3
+        name: Elixir Deps Cache
+        env:
+          cache-name: cache-elixir-deps
+        with:
+          path: deps
+          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
+          restore-keys: |
+            ${{ runner.os }}-${{ env.cache-name }}-
+      - uses: actions/cache@v3
+        name: Elixir Build Cache
+        env:
+          cache-name: cache-elixir-build
+        with:
+          path: _build
+          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/mix.lock') }}
+      - name: Install Dependencies
+        run: mix deps.get --only $MIX_ENV
+      - name: Compile Dependencies
+        run: mix deps.compile --skip-umbrella-children
+      - name: Compile Application
+        run: mix compile
+      - name: Setup Database
+        run: |
+          mix ecto.create
+          mix ecto.migrate
+      - name: Run Tests and Upload Coverage Report
+        env:
+          E2E_MAX_WAIT_SECONDS: 20
+        run: |
+          # XXX: This can fail when coveralls is down
+          mix coveralls.github --umbrella
+      - name: Test Report
+        uses: dorny/test-reporter@v1
+        if: success() || failure()
+        with:
+          name: Elixir Unit Test Report
+          path: _build/test/lib/*/test-junit-report.xml
+          reporter: java-junit
+  acceptance-test:
+    runs-on: ubuntu-latest
+    env:
+      MIX_ENV: test
+      POSTGRES_HOST: localhost
+      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+      MIX_TEST_PARTITIONS: 4
+    strategy:
+      fail-fast: false
+      matrix:
+        MIX_TEST_PARTITION: [1, 2, 3, 4]
+    services:
+      postgres:
+        image: postgres:15
+        ports:
+          - 5432:5432
+        env:
+          POSTGRES_USER: postgres
+          POSTGRES_PASSWORD: postgres
+        options: >-
+          --health-cmd pg_isready
+          --health-interval 10s
+          --health-timeout 5s
+          --health-retries 5
       vault:
         image: vault:1.12.2
         env:
@@ -104,8 +178,7 @@ jobs:
         env:
           E2E_MAX_WAIT_SECONDS: 20
         run: |
-          # XXX: This can fail when coveralls is down
-          mix coveralls.github --umbrella
+          mix test --only acceptance:true --partitions=${{ matrix.MIX_TEST_PARTITIONS }}
       - name: Save Screenshots
         if: success() || failure()
         uses: actions/upload-artifact@v3
@@ -116,6 +189,6 @@ jobs:
         uses: dorny/test-reporter@v1
         if: success() || failure()
         with:
-          name: Elixir Test Report
+          name: Elixir Acceptance Test Report
           path: _build/test/lib/*/test-junit-report.xml
           reporter: java-junit
